Add msm_sde_rotator.h header
Header is needed to compile Display HAL
hardware/qcom/display/msm8998/sdm/libs/core/drm/hw_info_drm.cpp:36:10: fatal error: 'media/msm_sde_rotator.h' file not found

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>