cp_headers: Include drm and drm_mode headers
On the new media HAL the `drm_fourcc.h` header is actually used,
transitively including drm.h:

    In file included from vendor/qcom/opensource/display/gralloc/gr_utils.cpp:34:
    kernel/sony/msm-4.14/common-headers/kernel-headers/drm/drm_fourcc.h:21:10: fatal error: 'drm.h' file not found
    #include "drm.h"
             ^~~~~~~

Same for `drm_mode`, of which an incomplete/dated one would otherwise be
picked from elsewhere (bionic).

In addition, sort the `drm/` entries.